---
name: List repo

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  list-repo:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2

    # - name: List Repo
    #   run: |
    #     cd path

    - name: List Repo
      run: ls
    - name: show env1
      run: |
        echo $GITHUB_EVENT_NAME
    - name: show env2
      run: |
        echo $GITHUB_REPOSITORY_OWNER	
    - name: show env3
      run: |
        echo $matrix.tag
    - name: show env4
      run: |
        echo $matrix.target
    

    