---
name: push on main or PR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  list-repo:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2

    - name: who triggered
      run: echo "$GITHUB_EVENT_NAME"	

    - name: Generate Vars
      id: generate_vars
      run: |
        # Just Tag
        IMAGE_TAG=sha-$(echo $(git rev-parse --short HEAD) | cut -c1-7)
        # Just Image name
        IMAGE_NAME=${{ github.repository }}
        #Image ID= Name + Tag
        IMAGE_ID=$IMAGE_NAME:$IMAGE_TAG
        IMAGE=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')
        echo "Image: $IMAGE"
        echo "::set-output name=image::$IMAGE"
        echo "::set-output name=image_name::$IMAGE_ID"
        echo "::set-output name=image_tag::$IMAGE_TAG"
        echo ""

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}



    - name: Build  and push Docker Image
      run: |
        docker build -t ${{ steps.generate_vars.outputs.image }}  .
        docker push ${{ steps.generate_vars.outputs.image }}

    - name: Clone symbiosis repo
      uses: actions/checkout@master
      with:
        repository: hasnain28/symbiosis

    - name: cd into repo and execute
      run: |
        cd cluster
        cd cv
        yq eval -i '.spec.values.deployment.image.tag ="'${{ steps.generate_vars.outputs.image }}'"' "${file}"
        yq eval -i '.spec.values.deployment.image.tag ="'${tag}'"' "${file}"
        git add "${file}"
        git commit -m "update helm release.yaml"
        git push
      env:        
        file: helm-release.yaml 


        


    