name: pull request

on: 
  push:
    branches:
      - master
      - feat/actions

jobs:
  list-repo:
    runs-on: ubuntu-latest
    steps:
    - name: print env
      run:  echo ${{ github.event.pull_request.base.ref }}
    - name: print source
      run:  echo ${GITHUB_HEAD_REF}	
    

      
        