name: pull request

on: 
  push:
    branches:
      - master
      - feat/actions

jobs:
  list-repo:
    runs-on: ubuntu-latest
    steps:
    - name: print env
      run: $ echo ${GITHUB_REF##*/}

      
        